USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS GOLD;

--SALES by state
CREATE OR REPLACE TABLE GOLD.SALES_BY_STATE AS
SELECT 
  d.state,
  SUM(f.sales_price) AS total_sales
FROM SILVER.FACT_SALES f
JOIN SILVER.CUSTOMER_DIM d
 ON f.customer_sk=d.CUSTOMER_SK
 GROUP BY d.state;


 SELECT * FROM SILVER.CUSTOMER_DIM LIMIT 5;

 SELECT * FROM SILVER.FACT_SALES LIMIT 5;

---sales by year
 CREATE OR REPLACE TABLE GOLD.SALES_BY_YEAR AS
 SELECT 
   YEAR(transaction_date) AS sales_year,
   SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY sales_year;

--sales by store every month

CREATE OR REPLACE TABLE GOLD.MONTHLY_SALES AS
SELECT 
   DATE_TRUNC('month',transaction_date) AS sales_month,
   SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY sales_month;

--Top 10 stores by sales
CREATE OR REPLACE TABLE GOLD.TOP_sTORES AS
SELECT
  store_id,
  SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY store_id
ORDER BY total_sales DESC
LIMIT 10;

SELECT * FROM GOLD.SALES_BY_STATE LIMIT 5;

--performance validation
SELECT COUNT(*) FROM GOLD.SALES_BY_STATE;

SELECT COUNT(*) FROM GOLD.SALES_BY_YEAR;
SELECT COUNT(*) FROM GOLD.MONTHLY_SALES;
SELECT COUNT(*) FROM GOLD.TOP_STORES;

SELECT * FROM SILVER.FACT_SALES LIMIT 5;

SELECT SUM(sales_price) FROM SILVER.FACT_SALES;

SELECT SUM(total_sales) FROM GOLD.SALES_BY_STATE;

SELECT SUM(total_sales) FROM GOLD.SALES_BY_YEAR;